use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Error {
    MatchNotFound = 1,
    AlreadyFunded = 2,
    NotFunded = 3,
    Unauthorized = 4,
    InvalidState = 5,
    AlreadyExists = 6,
    AlreadyInitialized = 7,
    Overflow = 8,
    ContractPaused = 9,
    InvalidAmount = 10,
    MatchCancelled = 11,
    MatchCompleted = 12,
    DuplicateGameId = 13,
    MatchNotExpired = 14,
    InvalidGameId = 15,
    InvalidPlayers = 16,
    TokenNotAllowed = 17,
    InvalidAddress = 18,
    MatchAlreadyActive = 19,
    InvalidTimeout = 20,
    SnapshotNotFound = 21,
    PendingResultNotFound = 22,
    DisputePeriodNotElapsed = 23,
    DisputeAlreadyRaised = 24,
    VotingPeriodNotElapsed = 25,
    VotingPeriodElapsed = 26,
    AlreadyVoted = 27,
    NotStaker = 28,
    DisputeNotFound = 29,
    DisputeAlreadyResolved = 30,
    InvalidEvidenceHash = 31,
    MatchNotInPendingResult = 32,
}
